apiVersion: apps/v1
kind: Deployment
metadata:
  name: acitbuggy-deployment
  labels:
    app: acitbuggy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acitbuggy
  template:
    metadata:
      labels:
        app: acitbuggy
    spec:
      containers:
        - name: acitbuggy
          image: 124355683348.dkr.ecr.us-east-2.amazonaws.com/asg:1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: acitbuggy
  labels:
    app: acitbuggy
spec:
  type: LoadBalancer
  selector:
    app: acitbuggy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

